"""Translate the two locked EOD ETF strategies into historical option outcomes.

The underlying rules are generated by ``eod_best_strategy_lab`` and remain
unchanged. This module maps each underlying entry/exit into the targeted Alpaca
historical options archive and evaluates:

* 0DTE, front, weekly, and swing expiration buckets;
* ATM calls, approximately 0.75% OTM calls, and ATM/OTM vertical call spreads;
* base, worse, and severe execution models.

Execution is deliberately conservative: long legs enter at the observed minute
high plus modeled slippage and exit at the observed minute low minus modeled
slippage. Vertical legs are reconstructed independently with rational payoff
bounds. Per-contract fees are included. Five-minute underlying target/stop bars
are translated to the first option minute after the five-minute bar closes, so
no option price from before the underlying trigger is used.

Research only. No order-routing or paper-trading code is present.
"""
from __future__ import annotations

import argparse
import csv
import json
import math
from collections import defaultdict
from dataclasses import asdict, dataclass
from datetime import date, datetime, time, timedelta, timezone
from pathlib import Path
from statistics import mean, median
from typing import Any, Sequence

import numpy as np

from eod_best_strategy_lab import (
    iwm_extreme_reversal_trades,
    qqq_confirmed_reversal_trades,
)
from eod_option_pattern_lab import (
    BUCKETS,
    DEFAULT_ARCHIVE_ROOT,
    DEFAULT_EQUITY_DB,
    EXECUTION_MODELS,
    STRUCTURES,
    OptionArchive,
    OptionOutcome,
    Timing,
    simulate_outcome,
)
from eod_pattern_lab import block_bootstrap_ci, load_sessions


CORE = Path(__file__).resolve().parent
ROOT = CORE.parent
DEFAULT_OUT = ROOT / "data" / "eod_best_strategy_options_lab"
ANALYSIS_START = date(2026, 1, 26)
RECENT_START = date(2026, 4, 25)


@dataclass(frozen=True, slots=True)
class StrategySignal:
    strategy_id: str
    strategy_name: str
    symbol: str
    day: str
    entry_time_et: str
    option_exit_time_et: str
    underlying_exit_time_et: str
    underlying_exit_reason: str
    underlying_raw_return_pct: float
    selection_checkpoint: str


@dataclass(slots=True)
class OptionTradeRow:
    strategy_id: str
    strategy_name: str
    symbol: str
    day: str
    underlying_exit_reason: str
    underlying_raw_return_pct: float
    bucket: str
    structure: str
    execution_model: str
    exit_policy: str
    entry_time_et: str
    exit_time_et: str
    long_contract: str | None
    long_expiration: str | None
    long_strike: float | None
    short_contract: str | None
    short_strike: float | None
    entry_debit: float | None
    exit_value: float | None
    fees_dollars: float | None
    risk_capital_dollars: float | None
    pnl_dollars: float | None
    return_on_risk_pct: float | None
    status: str
    skip_reason: str | None


@dataclass(slots=True)
class VariantResult:
    strategy_id: str
    strategy_name: str
    symbol: str
    bucket: str
    structure: str
    execution_model: str
    exit_policy: str
    signal_n: int
    executed_n: int
    coverage_pct: float | None
    mean_return_pct: float | None
    median_return_pct: float | None
    trimmed_mean_pct: float | None
    win_rate_pct: float | None
    profit_factor: float | None
    mean_pnl_dollars: float | None
    total_pnl_dollars: float | None
    median_risk_capital_dollars: float | None
    bootstrap_ci_low_pct: float | None
    bootstrap_ci_high_pct: float | None
    exclude_best_1_mean_pct: float | None
    exclude_best_3_mean_pct: float | None
    first_half_mean_pct: float | None
    second_half_mean_pct: float | None
    recent_n: int
    recent_mean_pct: float | None
    recent_median_pct: float | None
    recent_win_rate_pct: float | None
    best_return_pct: float | None
    worst_return_pct: float | None
    max_drawdown_dollars: float | None
    max_losing_streak: int | None
    robust_positive: bool


def _parse_clock(raw: str) -> time:
    hour, minute = (int(part) for part in raw.split(":", 1))
    return time(hour, minute)


def _option_exit_clock(underlying_exit_time: str) -> str:
    """Move a five-minute trigger to the first minute after that bar closes."""
    if underlying_exit_time == "16:00":
        return "15:59"
    clock = _parse_clock(underlying_exit_time)
    moved = datetime.combine(date(2000, 1, 1), clock) + timedelta(minutes=5)
    if moved.time() >= time(16, 0):
        return "15:59"
    return moved.strftime("%H:%M")


def build_signals(sessions: dict[str, list[dict[str, Any]]]) -> list[StrategySignal]:
    qqq = qqq_confirmed_reversal_trades(sessions)
    iwm = iwm_extreme_reversal_trades(sessions)
    signals: list[StrategySignal] = []
    for trade in qqq + iwm:
        if trade.day < ANALYSIS_START.isoformat():
            continue
        checkpoint = "price_1530" if trade.strategy_id == "qqq_confirmed_reversal" else "price_1500"
        signals.append(
            StrategySignal(
                strategy_id=trade.strategy_id,
                strategy_name=trade.strategy_name,
                symbol=trade.symbol,
                day=trade.day,
                entry_time_et=trade.entry_time,
                option_exit_time_et=_option_exit_clock(trade.exit_time),
                underlying_exit_time_et=trade.exit_time,
                underlying_exit_reason=trade.exit_reason,
                underlying_raw_return_pct=trade.raw_return_pct,
                selection_checkpoint=checkpoint,
            )
        )
    return sorted(signals, key=lambda row: (row.day, row.strategy_id))


def _safe_mean(values: Sequence[float]) -> float | None:
    return mean(values) if values else None


def _trimmed_mean(values: Sequence[float], proportion: float = 0.10) -> float | None:
    if not values:
        return None
    ordered = sorted(values)
    trim = int(len(ordered) * proportion)
    if trim and len(ordered) > trim * 2:
        ordered = ordered[trim:-trim]
    return mean(ordered)


def _exclude_best(values: Sequence[float], count: int) -> float | None:
    if len(values) <= count:
        return None
    return mean(sorted(values)[:-count])


def _profit_factor(pnls: Sequence[float]) -> float | None:
    gains = sum(value for value in pnls if value > 0)
    losses = -sum(value for value in pnls if value < 0)
    if losses > 0:
        return gains / losses
    return math.inf if gains > 0 else None


def _max_drawdown(pnls: Sequence[float]) -> float | None:
    if not pnls:
        return None
    equity = peak = 0.0
    drawdown = 0.0
    for pnl in pnls:
        equity += pnl
        peak = max(peak, equity)
        drawdown = min(drawdown, equity - peak)
    return drawdown


def _max_losing_streak(values: Sequence[float]) -> int:
    current = best = 0
    for value in values:
        if value < 0:
            current += 1
            best = max(best, current)
        else:
            current = 0
    return best


def translate_signal(
    signal: StrategySignal,
    archive: OptionArchive,
    session_by_day: dict[str, dict[str, Any]],
    bucket: str,
    structure: str,
    execution_model: Any,
    exit_policy: str,
) -> OptionTradeRow:
    exit_clock = signal.option_exit_time_et if exit_policy == "underlying_exit" else "15:59"
    timing = Timing(
        entry_day=signal.day,
        entry_clock=_parse_clock(signal.entry_time_et),
        exit_day=signal.day,
        exit_clock=_parse_clock(exit_clock),
        selection_checkpoint=signal.selection_checkpoint,
        close_entry_hypothetical=False,
    )
    outcome: OptionOutcome = simulate_outcome(
        archive=archive,
        session_by_day=session_by_day,
        decision_day=signal.day,
        timing=timing,
        actual_side="long",
        bucket=bucket,
        structure=structure,
        execution=execution_model,
    )
    return OptionTradeRow(
        strategy_id=signal.strategy_id,
        strategy_name=signal.strategy_name,
        symbol=signal.symbol,
        day=signal.day,
        underlying_exit_reason=signal.underlying_exit_reason,
        underlying_raw_return_pct=signal.underlying_raw_return_pct,
        bucket=bucket,
        structure=structure,
        execution_model=execution_model.name,
        exit_policy=exit_policy,
        entry_time_et=signal.entry_time_et,
        exit_time_et=exit_clock,
        long_contract=outcome.long_contract,
        long_expiration=outcome.long_expiration,
        long_strike=outcome.long_strike,
        short_contract=outcome.short_contract,
        short_strike=outcome.short_strike,
        entry_debit=outcome.entry_debit,
        exit_value=outcome.exit_value,
        fees_dollars=outcome.fees_dollars,
        risk_capital_dollars=outcome.risk_capital_dollars,
        pnl_dollars=outcome.pnl_dollars,
        return_on_risk_pct=outcome.return_on_risk_pct,
        status=outcome.status,
        skip_reason=outcome.skip_reason,
    )


def evaluate_variant(
    strategy_id: str,
    strategy_name: str,
    symbol: str,
    bucket: str,
    structure: str,
    execution_model: str,
    exit_policy: str,
    signal_n: int,
    rows: Sequence[OptionTradeRow],
) -> VariantResult:
    executed = [
        row for row in rows
        if row.status == "executed"
        and row.return_on_risk_pct is not None
        and row.pnl_dollars is not None
        and row.risk_capital_dollars is not None
    ]
    values = [float(row.return_on_risk_pct) for row in executed]
    pnls = [float(row.pnl_dollars) for row in executed]
    risks = [float(row.risk_capital_dollars) for row in executed]
    recent = [row for row in executed if row.day >= RECENT_START.isoformat()]
    recent_values = [float(row.return_on_risk_pct) for row in recent]
    midpoint = len(values) // 2
    if len(values) >= 5:
        seed = abs(hash((strategy_id, bucket, structure, execution_model))) % (2**32)
        ci_low, ci_high = block_bootstrap_ci(np.asarray(values, dtype=float), seed)
    else:
        ci_low = ci_high = None
    mean_value = _safe_mean(values)
    median_value = median(values) if values else None
    recent_mean = _safe_mean(recent_values)
    ex_best_1 = _exclude_best(values, 1)
    # Cross-execution robustness is assigned after all matching base/worse/
    # severe rows have been evaluated.
    robust_positive = False
    return VariantResult(
        strategy_id=strategy_id,
        strategy_name=strategy_name,
        symbol=symbol,
        bucket=bucket,
        structure=structure,
        execution_model=execution_model,
        exit_policy=exit_policy,
        signal_n=signal_n,
        executed_n=len(values),
        coverage_pct=(len(values) / signal_n * 100.0) if signal_n else None,
        mean_return_pct=mean_value,
        median_return_pct=median_value,
        trimmed_mean_pct=_trimmed_mean(values),
        win_rate_pct=(sum(value > 0 for value in values) / len(values) * 100.0) if values else None,
        profit_factor=_profit_factor(pnls),
        mean_pnl_dollars=_safe_mean(pnls),
        total_pnl_dollars=sum(pnls) if pnls else None,
        median_risk_capital_dollars=median(risks) if risks else None,
        bootstrap_ci_low_pct=ci_low,
        bootstrap_ci_high_pct=ci_high,
        exclude_best_1_mean_pct=ex_best_1,
        exclude_best_3_mean_pct=_exclude_best(values, 3),
        first_half_mean_pct=_safe_mean(values[:midpoint]) if midpoint else None,
        second_half_mean_pct=_safe_mean(values[midpoint:]),
        recent_n=len(recent_values),
        recent_mean_pct=recent_mean,
        recent_median_pct=median(recent_values) if recent_values else None,
        recent_win_rate_pct=(sum(value > 0 for value in recent_values) / len(recent_values) * 100.0) if recent_values else None,
        best_return_pct=max(values) if values else None,
        worst_return_pct=min(values) if values else None,
        max_drawdown_dollars=_max_drawdown(pnls),
        max_losing_streak=_max_losing_streak(values) if values else None,
        robust_positive=robust_positive,
    )


def write_csv(path: Path, rows: Sequence[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    fields = list(rows[0].keys())
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def _fmt(value: Any, suffix: str = "") -> str:
    if value is None:
        return "n/a"
    if isinstance(value, float) and not math.isfinite(value):
        return "inf"
    return f"{float(value):.2f}{suffix}"


def build_report(summary: dict[str, Any]) -> str:
    lines = [
        "# Locked EOD Strategies — Historical Options Translation",
        "",
        f"**Generated:** {summary['generated_at']}",
        "",
        "## Scope",
        "",
        f"- Option archive: {summary['analysis_start']} through {summary['analysis_end']}",
        f"- QQQ signals: {summary['signal_counts'].get('qqq_confirmed_reversal', 0)}",
        f"- IWM signals: {summary['signal_counts'].get('iwm_extreme_reversal', 0)}",
        "- Calls only, because both underlying strategies are long reversals.",
        "- Underlying target/stop bars are translated to the first option minute after the five-minute trigger bar closes.",
        "",
        "## Best base-execution variants",
        "",
        "| Strategy | Exit policy | Bucket | Structure | N | Coverage | Mean | Median | Win rate | Ex-best-1 | Recent mean | Median capital | Total P/L |",
        "|---|---|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for row in summary["best_base_variants"]:
        lines.append(
            f"| {row['strategy_name']} | {row['exit_policy']} | {row['bucket']} | {row['structure']} | {row['executed_n']} | "
            f"{_fmt(row['coverage_pct'], '%')} | {_fmt(row['mean_return_pct'], '%')} | "
            f"{_fmt(row['median_return_pct'], '%')} | {_fmt(row['win_rate_pct'], '%')} | "
            f"{_fmt(row['exclude_best_1_mean_pct'], '%')} | {_fmt(row['recent_mean_pct'], '%')} | "
            f"${_fmt(row['median_risk_capital_dollars'])} | ${_fmt(row['total_pnl_dollars'])} |"
        )
    lines.extend(
        [
            "",
            "## Cost stress for each best base variant",
            "",
            "| Strategy | Exit policy | Bucket | Structure | Execution | N | Mean | Median | Win rate | Ex-best-1 | Total P/L |",
            "|---|---|---|---|---|---:|---:|---:|---:|---:|---:|",
        ]
    )
    for row in summary["best_variant_stress"]:
        lines.append(
            f"| {row['strategy_name']} | {row['exit_policy']} | {row['bucket']} | {row['structure']} | {row['execution_model']} | "
            f"{row['executed_n']} | {_fmt(row['mean_return_pct'], '%')} | {_fmt(row['median_return_pct'], '%')} | "
            f"{_fmt(row['win_rate_pct'], '%')} | {_fmt(row['exclude_best_1_mean_pct'], '%')} | "
            f"${_fmt(row['total_pnl_dollars'])} |"
        )
    lines.extend(
        [
            "",
            "## Verdict",
            "",
            summary["verdict"],
            "",
            "## Important constraints",
            "",
            "- Historical NBBO, implied volatility, Greeks, and quote-size history are unavailable. Results use conservative OPRA minute trade bars.",
            "- The sample is small: 16 QQQ signals and 12 IWM signals before option-data coverage losses.",
            "- Large percentage returns on cheap 0DTE contracts can be dominated by a few convex winners; exclusion tests are therefore emphasized.",
            "- Option results are not directly comparable with the underlying ETF return because option risk capital and convexity differ.",
            "- No variant is suitable for live deployment without prospective quote-level paper capture.",
            "",
            "## Output files",
            "",
        ]
    )
    for label, path in summary["files"].items():
        lines.append(f"- `{label}`: `{path}`")
    return "\n".join(lines) + "\n"


def run(args: argparse.Namespace) -> dict[str, Any]:
    equity_db = Path(args.equity_db or DEFAULT_EQUITY_DB).resolve()
    archive_root = Path(args.archive_root or DEFAULT_ARCHIVE_ROOT).resolve()
    output_dir = Path(args.output_dir or DEFAULT_OUT).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    sessions = load_sessions(equity_db)
    signals = build_signals(sessions)
    session_by_symbol_day = {
        symbol: {row["day"]: row for row in rows}
        for symbol, rows in sessions.items()
    }
    archives = {
        symbol: OptionArchive(
            symbol,
            archive_root / symbol.lower() / "historical_options.sqlite",
        )
        for symbol in ("QQQ", "IWM")
    }

    trade_rows: list[OptionTradeRow] = []
    try:
        for signal in signals:
            archive = archives[signal.symbol]
            session_by_day = session_by_symbol_day[signal.symbol]
            for bucket in BUCKETS:
                for structure in STRUCTURES:
                    for execution_model in EXECUTION_MODELS:
                        for exit_policy in ("underlying_exit", "hold_to_close"):
                            trade_rows.append(
                                translate_signal(
                                    signal,
                                    archive,
                                    session_by_day,
                                    bucket,
                                    structure,
                                    execution_model,
                                    exit_policy,
                                )
                            )
    finally:
        for archive in archives.values():
            archive.close()

    grouped: dict[tuple[str, str, str, str, str], list[OptionTradeRow]] = defaultdict(list)
    for row in trade_rows:
        grouped[(row.strategy_id, row.bucket, row.structure, row.execution_model, row.exit_policy)].append(row)
    signal_counts: dict[str, int] = defaultdict(int)
    strategy_names: dict[str, str] = {}
    strategy_symbols: dict[str, str] = {}
    for signal in signals:
        signal_counts[signal.strategy_id] += 1
        strategy_names[signal.strategy_id] = signal.strategy_name
        strategy_symbols[signal.strategy_id] = signal.symbol

    results: list[VariantResult] = []
    for (strategy_id, bucket, structure, execution_model, exit_policy), rows in sorted(grouped.items()):
        results.append(
            evaluate_variant(
                strategy_id,
                strategy_names[strategy_id],
                strategy_symbols[strategy_id],
                bucket,
                structure,
                execution_model,
                exit_policy,
                signal_counts[strategy_id],
                rows,
            )
        )

    best_base: list[VariantResult] = []
    for strategy_id in sorted(signal_counts):
        candidates = [
            row for row in results
            if row.strategy_id == strategy_id
            and row.execution_model == "base"
            and row.executed_n >= max(5, math.ceil(signal_counts[strategy_id] * 0.50))
            and row.mean_return_pct is not None
        ]
        candidates.sort(
            key=lambda row: (
                row.mean_return_pct if row.mean_return_pct is not None else -math.inf,
                row.exclude_best_1_mean_pct if row.exclude_best_1_mean_pct is not None else -math.inf,
                row.executed_n,
            ),
            reverse=True,
        )
        if candidates:
            best_base.append(candidates[0])

    stress_rows: list[VariantResult] = []
    for best in best_base:
        stress_rows.extend(
            sorted(
                [
                    row for row in results
                    if row.strategy_id == best.strategy_id
                    and row.bucket == best.bucket
                    and row.structure == best.structure
                    and row.exit_policy == best.exit_policy
                ],
                key=lambda row: ("base", "worse", "severe").index(row.execution_model),
            )
        )

    result_index = {
        (row.strategy_id, row.bucket, row.structure, row.exit_policy, row.execution_model): row
        for row in results
    }
    for row in results:
        if row.execution_model != "base":
            continue
        worse = result_index.get((row.strategy_id, row.bucket, row.structure, row.exit_policy, "worse"))
        severe = result_index.get((row.strategy_id, row.bucket, row.structure, row.exit_policy, "severe"))
        row.robust_positive = bool(
            worse is not None and severe is not None
            and row.executed_n >= 8
            and row.mean_return_pct is not None and row.mean_return_pct > 0
            and row.median_return_pct is not None and row.median_return_pct > 0
            and row.exclude_best_1_mean_pct is not None and row.exclude_best_1_mean_pct > 0
            and row.exclude_best_3_mean_pct is not None and row.exclude_best_3_mean_pct > 0
            and row.recent_mean_pct is not None and row.recent_mean_pct > 0
            and worse.mean_return_pct is not None and worse.mean_return_pct > 0
            and worse.median_return_pct is not None and worse.median_return_pct > 0
            and worse.exclude_best_1_mean_pct is not None and worse.exclude_best_1_mean_pct > 0
            and severe.mean_return_pct is not None and severe.mean_return_pct > 0
        )
    robust = [row for row in results if row.robust_positive]
    if robust:
        verdict = (
            f"{len(robust)} variant-execution rows cleared the preliminary positive gate, but none should be considered validated "
            "without quote-level forward observation and stability under worse/severe fills."
        )
    else:
        verdict = (
            "No option translation cleared the preliminary robustness gate across average, median, exclusion of the best trade, "
            "and recent performance. The underlying ETF strategies remain materially stronger than their long-option translations."
        )

    generated_at = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
    files = {
        "report_markdown": str(output_dir / "report.md"),
        "report_json": str(output_dir / "report.json"),
        "variant_results_csv": str(output_dir / "variant_results.csv"),
        "option_trade_log_csv": str(output_dir / "option_trade_log.csv"),
        "signals_csv": str(output_dir / "signals.csv"),
    }
    summary = {
        "generated_at": generated_at,
        "analysis_start": min(signal.day for signal in signals) if signals else None,
        "analysis_end": max(signal.day for signal in signals) if signals else None,
        "signal_counts": dict(signal_counts),
        "option_trade_rows": len(trade_rows),
        "executed_option_rows": sum(row.status == "executed" for row in trade_rows),
        "skipped_option_rows": sum(row.status != "executed" for row in trade_rows),
        "variant_results": [asdict(row) for row in results],
        "best_base_variants": [asdict(row) for row in best_base],
        "best_variant_stress": [asdict(row) for row in stress_rows],
        "robust_positive_rows": [asdict(row) for row in robust],
        "verdict": verdict,
        "files": files,
    }
    write_csv(output_dir / "signals.csv", [asdict(row) for row in signals])
    write_csv(output_dir / "option_trade_log.csv", [asdict(row) for row in trade_rows])
    write_csv(output_dir / "variant_results.csv", [asdict(row) for row in results])
    (output_dir / "report.json").write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")
    (output_dir / "report.md").write_text(build_report(summary), encoding="utf-8")
    return summary


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Historical option translation of the two locked EOD strategies.")
    parser.add_argument("--equity-db")
    parser.add_argument("--archive-root")
    parser.add_argument("--output-dir")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    summary = run(build_parser().parse_args(argv))
    print(json.dumps({
        "signal_counts": summary["signal_counts"],
        "option_trade_rows": summary["option_trade_rows"],
        "executed_option_rows": summary["executed_option_rows"],
        "skipped_option_rows": summary["skipped_option_rows"],
        "best_base_variants": summary["best_base_variants"],
        "best_variant_stress": summary["best_variant_stress"],
        "robust_positive_rows": summary["robust_positive_rows"],
        "verdict": summary["verdict"],
        "files": summary["files"],
    }, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
