"use client";
import { useEffect, useMemo, useState } from "react";
import { createJournalEntry, fetchBars, fetchChartTemplates, fetchFlow, fetchMatrix, fetchOptionsChain, listScanHistory, loadSavedScan, saveChartTemplate, type ChartTemplate, type RealBar } from "@/lib/api";

const W=1100,H=520, TOP=18, PRICE_H=390, VOL_H=85;
function ema(rows: RealBar[], length: number) { const alpha=2/(length+1); let value: number | null=null; return rows.map((r) => value=value==null?r.close:alpha*r.close+(1-alpha)*value); }
function vwap(rows: RealBar[]) { let pv=0,v=0; return rows.map((r) => { pv+=((r.high+r.low+r.close)/3)*r.volume; v+=r.volume; return v?pv/v:r.close; }); }
function path(values:number[], x:(i:number)=>number, y:(v:number)=>number) { return values.map((v,i)=>`${i?"L":"M"}${x(i).toFixed(1)},${y(v).toFixed(1)}`).join(" "); }
function extended(iso:string) { const t=new Date(iso).toLocaleTimeString("en-US",{timeZone:"America/New_York",hour12:false,hour:"2-digit",minute:"2-digit"}); return t<"09:30"||t>="16:00"; }

export function ChartWorkbench({ ticker }: { ticker:string }) {
  const [timeframe,setTimeframe]=useState("5m"),[limit,setLimit]=useState(240),[offset,setOffset]=useState(0),[bars,setBars]=useState<RealBar[]>([]),[error,setError]=useState("");
  const [show9,setShow9]=useState(true),[show20,setShow20]=useState(true),[showVwap,setShowVwap]=useState(true),[showVolume,setShowVolume]=useState(true),[showExtended,setShowExtended]=useState(true);
  const [drawings,setDrawings]=useState<number[]>([]),[gex,setGex]=useState<Array<{label:string;price:number}>>([]),[flow,setFlow]=useState<Array<{time:string;premium:number;side:string}>>([]),[signal,setSignal]=useState<string|null>(null),[strikes,setStrikes]=useState<number[]>([]);
  const [templates,setTemplates]=useState<ChartTemplate[]>([]),[templateName,setTemplateName]=useState("Intraday"),[message,setMessage]=useState("");
  useEffect(()=>{const c=new AbortController(); Promise.all([fetchBars(ticker,timeframe,c.signal,{limit:1000}),fetchMatrix(ticker,2,c.signal,"0.06"),fetchFlow(ticker,{minPremium:50000},c.signal),fetchOptionsChain(ticker,1,c.signal),listScanHistory({limit:1},c.signal),fetchChartTemplates(c.signal)]).then(async([b,m,f,o,h,t])=>{setBars(b.bars);setGex([["Call wall",m.summary.call_wall_strike],["Put wall",m.summary.put_wall_strike],["Gamma flip",m.summary.gamma_flip_level]].filter((x):x is [string,number]=>typeof x[1]==="number").map(([label,price])=>({label,price})));setFlow(f.prints.slice(0,100));setStrikes(o.expirations[0]?.rows.map((r)=>r.strike).sort((a,b)=>Math.abs(a-o.spot)-Math.abs(b-o.spot)).slice(0,4)??[]);setTemplates(t.templates);if(h.scans[0]){const saved=await loadSavedScan(h.scans[0].id,c.signal);const match=saved.top.find((x)=>x.ticker===ticker);setSignal(match?`${match.setup_type} ${match.direction} · ${saved.as_of}`:null);}}).catch((e)=>{if(!c.signal.aborted)setError(e instanceof Error?e.message:"Chart unavailable")});return()=>c.abort()},[ticker,timeframe]);
  const visible=useMemo(()=>bars.slice(Math.max(0,bars.length-offset-limit),bars.length-offset),[bars,offset,limit]); const e9=useMemo(()=>ema(visible,9),[visible]),e20=useMemo(()=>ema(visible,20),[visible]),vw=useMemo(()=>vwap(visible),[visible]);
  const geometry=useMemo(()=>{const prices=[...visible.flatMap((r)=>[r.low,r.high]),...drawings,...gex.map(x=>x.price),...strikes]; const lo=Math.min(...prices),hi=Math.max(...prices),pad=(hi-lo)*.04||1,domainHi=hi+pad,domainRange=hi-lo+2*pad; const x=(i:number)=>(i+.5)*W/Math.max(1,visible.length); const y=(v:number)=>TOP+(domainHi-v)/domainRange*PRICE_H; const valueAtY=(screenY:number)=>domainHi-(screenY-TOP)/PRICE_H*domainRange; const maxVol=Math.max(...visible.map(r=>r.volume),1); return {x,y,valueAtY,maxVol};},[visible,drawings,gex,strikes]);
  const state={ticker,timeframe,limit,show9,show20,showVwap,showVolume,showExtended,drawings,gex:true,flow:true,options:true};
  function apply(state:Record<string,unknown>){if(typeof state.timeframe==="string")setTimeframe(state.timeframe);if(typeof state.limit==="number")setLimit(state.limit);if(Array.isArray(state.drawings))setDrawings(state.drawings.filter((x):x is number=>typeof x==="number"));}
  async function saveTemplate(){await saveChartTemplate(templateName,state);setTemplates((await fetchChartTemplates()).templates);setMessage("Template saved server-side.");}
  async function saveJournal(){await createJournalEntry({ticker,title:`Chart review · ${ticker} · ${new Date().toLocaleString()}`,direction:"neutral",status:"planned",chart_state:state,thesis:`Chart snapshot with ${visible.length} ${timeframe} bars; ${signal??"no current saved-scan match"}.`});setMessage("Chart state linked to a journal draft.");}
  if(!visible.length)return <p style={{color:"var(--text-mute)"}}>{error||`Loading ${ticker} chart…`}</p>;
  return <div className="space-y-3" style={{color:"var(--text)"}}><section className="flex flex-wrap items-end gap-2 rounded-xl p-3" style={{background:"var(--panel)",border:"1px solid var(--line)"}}><div className="mr-auto"><h1 className="text-lg font-bold">Chart Workbench · {ticker}</h1><p className="text-[10px]" style={{color:"var(--text-mute)"}}>{visible[0]?.time} → {visible.at(-1)?.time} · click chart to add a horizontal drawing</p></div><select value={timeframe} onChange={e=>{setOffset(0);setTimeframe(e.target.value)}} className="rounded p-2 text-xs" style={{background:"var(--panel-2)"}}>{["1m","5m","15m","1h","1d"].map(x=><option key={x}>{x}</option>)}</select><select value={limit} onChange={e=>{setOffset(0);setLimit(Number(e.target.value))}} className="rounded p-2 text-xs" style={{background:"var(--panel-2)"}}>{[60,120,240,500].map(x=><option key={x}>{x} bars</option>)}</select><button onClick={()=>setOffset(Math.min(Math.max(0,bars.length-limit),offset+Math.floor(limit/2)))}>◀ older</button><button onClick={()=>setOffset(Math.max(0,offset-Math.floor(limit/2)))}>newer ▶</button>{[["EMA9",show9,setShow9],["EMA20",show20,setShow20],["VWAP",showVwap,setShowVwap],["Volume",showVolume,setShowVolume],["Extended",showExtended,setShowExtended]].map(([label,on,set])=><label key={String(label)} className="text-[10px]"><input type="checkbox" checked={on as boolean} onChange={e=>(set as (v:boolean)=>void)(e.target.checked)}/> {label as string}</label>)}</section>
  <div className="overflow-x-auto rounded-xl" style={{background:"var(--panel)",border:"1px solid var(--line)"}}><svg viewBox={`0 0 ${W} ${H}`} className="min-w-[760px]" role="img" aria-label={`${ticker} candlestick chart with volume and research overlays`} onClick={e=>{const rect=e.currentTarget.getBoundingClientRect();const sy=(e.clientY-rect.top)/rect.height*H;if(sy>TOP&&sy<TOP+PRICE_H)setDrawings(d=>[...d,geometry.valueAtY(sy)]);}}>
    {visible.map((r,i)=>showExtended&&extended(r.time)?<rect key={`x${i}`} x={geometry.x(i)-W/visible.length/2} y={0} width={W/visible.length} height={H} fill="var(--panel-2)" opacity=".45"/>:null)}
    {visible.map((r,i)=>{const x=geometry.x(i),up=r.close>=r.open,color=up?"var(--positive)":"var(--negative)",width=Math.max(1,W/visible.length*.55);return <g key={r.time}><line x1={x} x2={x} y1={geometry.y(r.high)} y2={geometry.y(r.low)} stroke={color}/><rect x={x-width/2} y={geometry.y(Math.max(r.open,r.close))} width={width} height={Math.max(1,Math.abs(geometry.y(r.open)-geometry.y(r.close)))} fill={color}/>{showVolume&&<rect x={x-width/2} y={H-8-r.volume/geometry.maxVol*VOL_H} width={width} height={r.volume/geometry.maxVol*VOL_H} fill={color} opacity=".35"/>}</g>})}
    {show9&&<path d={path(e9,geometry.x,geometry.y)} fill="none" stroke="#2ecc71" strokeWidth="1.5"/>}{show20&&<path d={path(e20,geometry.x,geometry.y)} fill="none" stroke="#e74c3c" strokeWidth="1.5"/>}{showVwap&&<path d={path(vw,geometry.x,geometry.y)} fill="none" stroke="#f1c40f" strokeWidth="1.5"/>}
    {gex.map(x=><g key={x.label}><line x1="0" x2={W} y1={geometry.y(x.price)} y2={geometry.y(x.price)} stroke="var(--accent)" strokeDasharray="6 4"/><text x="4" y={geometry.y(x.price)-3} fill="var(--accent)" fontSize="10">{x.label} {x.price.toFixed(2)}</text></g>)}
    {strikes.map(x=><line key={`s${x}`} x1="0" x2={W} y1={geometry.y(x)} y2={geometry.y(x)} stroke="var(--gold)" opacity=".25" strokeDasharray="2 4"/>)}
    {drawings.map((x,i)=><g key={`d${i}`}><line x1="0" x2={W} y1={geometry.y(x)} y2={geometry.y(x)} stroke="#fff"/><text x={W-55} y={geometry.y(x)-3} fill="#fff" fontSize="10">{x.toFixed(2)}</text></g>)}
    {flow.map((p,i)=>{const index=visible.findIndex(r=>r.time.slice(0,16)===p.time.slice(0,16));return index<0?null:<circle key={`${p.time}${i}`} cx={geometry.x(index)} cy={geometry.y(visible[index].high)} r={Math.min(8,2+Math.log10(Math.max(1,p.premium/1000)))} fill={p.side==="buy"?"#2dd4bf":"#fb7185"} opacity=".7"/>})}
  </svg></div>
  <section className="flex flex-wrap items-center gap-2 rounded-xl p-3 text-[10px]" style={{background:"var(--panel)",border:"1px solid var(--line)"}}><span style={{color:"var(--text-mute)"}}>Markers: GEX walls/flip (public-OI heuristic), ≥$50K option prints, nearest option strikes. {signal??"No active-ticker match in latest saved scan."}</span><button onClick={()=>setDrawings([])}>Clear drawings</button><input value={templateName} onChange={e=>setTemplateName(e.target.value)} className="rounded px-2 py-1" style={{background:"var(--panel-2)"}}/><button onClick={saveTemplate}>Save template</button><select onChange={e=>{const t=templates.find(x=>x.id===e.target.value);if(t)apply(t.state)}} defaultValue=""><option value="">Load template…</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><button onClick={saveJournal}>Link snapshot to journal</button>{message&&<span style={{color:"var(--positive)"}}>{message}</span>}</section></div>;
}
