"use client";
import { useEffect, useState } from "react";
import { fetchCompanyContext, type CompanyContext as Payload } from "@/lib/api";
const value = (v: number, unit: string) => unit === "USD" ? new Intl.NumberFormat("en-US", { notation: "compact", style: "currency", currency: "USD" }).format(v) : `${v.toLocaleString()} ${unit}`;
const card = "rounded-xl p-4 text-[11px]";
export function CompanyContext({ ticker }: { ticker: string }) {
  const [data, setData] = useState<Payload | null>(null); const [error, setError] = useState("");
  useEffect(() => { const c = new AbortController(); fetchCompanyContext(ticker, c.signal).then(setData).catch((e) => { if (!c.signal.aborted) setError(e instanceof Error ? e.message : "Context unavailable"); }); return () => c.abort(); }, [ticker]);
  if (!data) return <p style={{ color: "var(--text-mute)" }}>{error || `Loading official context for ${ticker}…`}</p>;
  return <div className="space-y-4" style={{ color: "var(--text)" }}>
    <section className={card} style={{ background: "var(--panel)", border: "1px solid var(--line)" }}><h1 className="text-xl font-bold">{data.profile?.name ?? ticker}</h1><p style={{ color: "var(--text-dim)" }}>{data.profile ? `${data.profile.exchanges.join(", ")} · SIC ${data.profile.sic} ${data.profile.sic_description} · FY ends ${data.profile.fiscal_year_end}` : "SEC profile unavailable for this symbol."}</p>{data.profile && <a href={data.profile.sec_company_url} target="_blank" rel="noreferrer" style={{ color: "var(--accent)" }}>Open official SEC company page</a>}</section>
    <div className="grid gap-3 lg:grid-cols-2"><section className={card} style={{ background: "var(--panel)", border: "1px solid var(--line)" }}><h2 className="mb-2 text-sm font-semibold">Latest filed fundamentals</h2>{data.fundamentals.map((x) => <div key={x.name} className="flex justify-between border-b py-2" style={{ borderColor: "var(--line)" }}><span>{x.name.replaceAll("_", " ")}<br/><small style={{ color: "var(--text-mute)" }}>{x.form} · period {x.end} · filed {x.filed}</small></span><b>{value(x.val, x.unit)}</b></div>)}</section><section className={card} style={{ background: "var(--panel)", border: "1px solid var(--line)" }}><h2 className="mb-2 text-sm font-semibold">Recent SEC filings</h2>{data.filings.map((x) => <p key={x.accession}><a href={x.url} target="_blank" rel="noreferrer" style={{ color: "var(--accent)" }}>{x.form} · filed {x.filed} · report {x.report_date}</a></p>)}</section></div>
    <div className="grid gap-3 lg:grid-cols-2"><section className={card} style={{ background: "var(--panel)", border: "1px solid var(--line)" }}><h2 className="mb-2 text-sm font-semibold">Earnings calendar</h2><p className="mb-2" style={{ color: "var(--gold)" }}>{data.earnings.status}</p>{data.earnings.events.map((event, i) => <div key={`${event.provider}-${event.scheduled_date}-${i}`} className="mb-2 rounded-lg border p-2" style={{ borderColor: event.conflict ? "var(--gold)" : "var(--line)" }}><b>{event.scheduled_date} · {event.timing}</b><br/><span style={{ color: "var(--text-mute)" }}>{event.status} · {event.provider}{event.conflict ? " · conflicting estimate" : ""}</span></div>)}{!data.earnings.events.length && <p>{data.earnings.detail}</p>}</section><section className={card} style={{ background: "var(--panel)", border: "1px solid var(--line)" }}><h2 className="mb-2 text-sm font-semibold">Corporate actions</h2><p style={{ color: "var(--gold)" }}>{data.corporate_actions.status}</p><p>{data.corporate_actions.detail}</p></section></div>
    <section className={card} style={{ background: "var(--panel)", border: "1px solid var(--line)" }}><h2 className="mb-2 text-sm font-semibold">Upcoming official macro calendar</h2>{data.macro.events.slice(0, 30).map((x, i) => <p key={`${x.date}-${x.title}-${i}`}><a href={x.source_url} target="_blank" rel="noreferrer" style={{ color: "var(--accent)" }}>{x.date} {x.time ?? ""} · {x.title}</a> <span style={{ color: "var(--text-mute)" }}>· {x.source}</span></p>)}</section>
    <p className="text-[10px]" style={{ color: "var(--text-mute)" }}>Generated {data.generated_at}. Earnings estimates remain source-labelled; conflicts are never silently resolved. No order capability.</p>
  </div>;
}
