"use client";

type Demo = {
  title: string;
  summary: string;
  metrics: [string, string][];
  rows: string[];
  next: string;
  locked?: string;
};

const DEMOS: Record<string, Demo> = {
  Autopilot: { title: "An AI agent you can audit before you trust", summary: "Premarket research becomes a bounded paper decision only after fresh evidence, closed-bar confirmation, contract liquidity, and deterministic risk gates agree.", metrics: [["Phase", "Waiting for confirmation"], ["Authority", "Alpaca paper only"], ["Risk gates", "8 of 8"]], rows: ["08:20 ET · Research agents produced thesis and counter-thesis", "09:42 ET · MU confirmation closed above the planned level", "09:42 ET · One liquid call passed spread, OI, cost, and freshness gates", "09:43 ET · Paper intent persisted before broker submission", "Exit, reconciliation, and every rejection remain in the audit ledger"], next: "Follow the evidence snapshot into Night Vision, then inspect the paper-order trace. This recorded run is illustrative; no real-money order is possible." },
  "Morning Brief": { title: "A two-minute plan before the bell", summary: "Regime, catalysts, exposure, and only the setups worth reviewing.", metrics: [["Regime", "Risk-on, selective"], ["MAG7 breadth", "5 of 7"], ["Event risk", "Elevated"]], rows: ["NVDA and MSFT lead relative strength", "META is nearest a high-gamma decision zone", "MU is the volatility focus; confirmation required"], next: "Inspect the highest-ranked setup and its invalidation." },
  "Earnings Radar": { title: "Catalysts ranked before the reaction", summary: "Expected move, revisions, historical reaction, and liquidity stay separate.", metrics: [["Liquid events", "6"], ["Universe", "MAG7 + leaders"], ["Validation", "Chronological"]], rows: ["MSFT · durable revisions, moderate implied move", "AMZN · wider tail risk, strong liquidity", "META · post-event drift historically mixed"], next: "Reject structures whose spread consumes the measured edge." },
  "Research Desk": { title: "One evidence trail from question to conclusion", summary: "Coordinates structure, options, history, catalysts, and adversarial review.", metrics: [["Agents", "5 bounded roles"], ["Sources", "Point-in-time"], ["Gate", "Human review"]], rows: ["Thesis and counter-thesis remain side by side", "Missing evidence stays unknown—not zero", "Every conclusion carries provenance and freshness"], next: "Begin with a falsifiable question, then inspect the evidence ledger." },
  "Ticker Workbench": { title: "One ticker, one evidence context", summary: "The live quote is temporarily unavailable, so Cipher is showing the safe workflow instead of an empty or stale price.", metrics: [["Source", "Demo fallback"], ["Scope", "Price · options · context"], ["Orders", "None"]], rows: ["Chart and options share the selected ticker", "Unavailable provider data stays unavailable", "Private research remains locked"], next: "Retry the live panel when provider access recovers." },
  "Night Vision": { title: "Price structure with honest exposure context", summary: "This fallback preserves the chart workflow without presenting synthetic levels as live market data.", metrics: [["Source", "Demo fallback"], ["GEX", "Public-OI heuristic"], ["Missing", "Unknown"]], rows: ["Premarket and regular sessions remain distinct", "Exposure is contextual—not verified dealer positioning", "Replay identity freezes what was known at decision time"], next: "Retry for a live Alpaca chart and current exposure snapshot." },
  "Strike Matrix": { title: "Options exposure without invented cells", summary: "This fallback explains the matrix while the bounded live Alpaca chain is unavailable.", metrics: [["Source", "Demo fallback"], ["Inputs", "Gamma · OI"], ["Missing", "Unknown"]], rows: ["Calls and puts retain signed exposure conventions", "Gamma or OI gaps never become zero", "Expiration and strike coverage remain visible"], next: "Retry for the live Alpaca-backed matrix." },
  "Setup Scanner": { title: "Rank opportunities, not noise", summary: "Liquid names where trend, levels, volatility, and options structure agree.", metrics: [["Scanned", "42"], ["Qualified", "4"], ["Rejected", "38 explained"]], rows: ["NVDA · continuation watch · evidence 84/100", "MU · PM rejection watch · evidence 79/100", "TSLA · breakout only after confirmation"], next: "Open a candidate to inspect its rejection funnel and snapshot ID." },
  "My Watchlists": { title: "A focused desk, not a ticker dump", summary: "Quotes, catalysts, and the latest qualifying setup in one list.", metrics: [["Demo list", "12"], ["Catalysts", "4"], ["Actionable", "3"]], rows: ["MAG7 core", "Semis · NVDA, AMD, MU, AVGO", "Indices · SPY and QQQ"], next: "Sign in to persist custom lists and tags.", locked: "Saving and editing watchlists is disabled for guests." },
  News: { title: "News attached to the thesis", summary: "Company, sector, macro, and earnings headlines grouped by decision impact.", metrics: [["High impact", "3"], ["Duplicates removed", "18"], ["Scope", "12 symbols"]], rows: ["AI capex read-through for semiconductors", "Rates sensitivity for long-duration technology", "Revisions separated from price commentary"], next: "Use headlines as catalyst evidence, never standalone direction." },
  "Options Terminal": { title: "Structure before prediction", summary: "Expiry, strikes, Greeks, liquidity, expected move, and bounded payoff.", metrics: [["Example", "NVDA call spread"], ["Max loss", "Debit paid"], ["Orders", "None"]], rows: ["Front-week IV compared with next expiry", "Bid/ask width is a first-class filter", "Breakeven and scenario payoff shown together"], next: "Choose the thesis horizon before choosing the contract." },
  Spyglass: { title: "Options flow with context", summary: "Clusters premium while refusing to equate flow with informed direction.", metrics: [["Focus", "Liquid prints"], ["Side", "Inferred"], ["OI", "Public snapshot"]], rows: ["Repeated NVDA call-side activity", "MU puts near a known level", "Index hedges separated from single-name bets"], next: "Confirm flow against price, volatility, and OI context." },
  "Company Context": { title: "Know what the ticker owns", summary: "Drivers, segments, revisions, valuation, catalysts, and thesis-break risks.", metrics: [["Example", "NVDA"], ["Drivers", "3 mapped"], ["Risk", "Expectations"]], rows: ["Secular demand separated from quarterly timing", "Suppliers and customers mapped", "Falsification evidence stated up front"], next: "Move from setup to business context without losing the question." },
  "Ask Cipher": { title: "An analyst that shows its work", summary: "Bounded questions, read-only tools, short context, and explicit uncertainty.", metrics: [["Tools", "Read-only"], ["Context", "Budgeted"], ["Output", "Evidence-linked"]], rows: ["Compare NVDA and AMD option structure", "Explain why MU failed a scanner gate", "Summarize catalyst concentration"], next: "Sign in to run tool-backed questions.", locked: "Anonymous LLM requests are disabled to protect rate limits and private context." },
  "Chart Workbench": { title: "Chart the decision, not decoration", summary: "Price, volume, VWAP, EMAs, sessions, and evidence snapshots.", metrics: [["Frames", "1m to daily"], ["Levels", "PM · PD · options"], ["State", "Read-only"]], rows: ["Premarket and RTH remain distinct", "Signals appear after confirmation", "Annotations retain source timestamps"], next: "Validate entry location and invalidation before the thesis." },
  "Portfolio Risk": { title: "Risk beyond ticker weights", summary: "Equity and option exposure normalized by delta, catalyst, and factor.", metrics: [["Demo NAV", "$100,000"], ["Net delta", "+0.31"], ["Top factor", "AI infra 38%"]], rows: ["NVDA and AVGO share factor risk", "Weekly options concentrate theta", "Earnings collisions flagged before sizing"], next: "Reduce correlated exposure before adding another idea." },
  Holdings: { title: "Stocks and options in one exposure view", summary: "Value, delta, catalysts, and scenario risk across instrument types.", metrics: [["Stocks", "4 demo"], ["Options", "2 defined-risk"], ["Broker", "Disconnected"]], rows: ["Options auto-included in totals", "Unknown Greeks remain unavailable", "Positions link to originating thesis"], next: "Connect private data after sign-in.", locked: "Guest holdings are illustrative and never connect to a broker." },
  Alerts: { title: "Alerts that encode the whole setup", summary: "Trigger, confirmation, invalidation, freshness, and source snapshot.", metrics: [["Demo alerts", "4"], ["Price-only", "0"], ["Orders", "None"]], rows: ["MU PMH reclaim after confirmed close", "NVDA gamma-wall break with liquidity", "META earnings-risk reminder"], next: "Sign in to create and deliver alerts.", locked: "Alert writes and delivery are disabled for guests." },
  "Paper Portfolios": { title: "Prospective evidence, never backfilled wins", summary: "Isolated paper ledgers for decisions, rejections, fills, exits, and equity.", metrics: [["Portfolios", "6 demo"], ["Authority", "Simulation"], ["Backfill", "Never"]], rows: ["No-setup differs from data failure", "Every rejection retains its reason", "Option P&L requires a real or labelled mark"], next: "Judge strategies from prospective samples and ledger truth." },
  "Trader Journal": { title: "A journal tied to evidence", summary: "Thesis, setup, plan, execution notes, outcome, and decision-time snapshot.", metrics: [["Demo entries", "8"], ["Mistakes tagged", "3"], ["Review", "Weekly"]], rows: ["Process errors separated from losses", "Screenshots retain levels and time", "Repeated mistakes become measurable"], next: "Sign in to keep a private journal.", locked: "Journal writes are disabled for guests." },
  Standing: { title: "Know what has earned trust", summary: "Maturity from hypothesis through backtest, paper, and mandatory review.", metrics: [["Research", "14"], ["Paper eligible", "6"], ["Live authorized", "0"]], rows: ["Sample size gates promotion", "Failures remain in lineage", "No path crosses LIVE_REVIEW_REQUIRED"], next: "Promote evidence quality, not attractive historical P&L." },
  Strategies: { title: "A catalog with assumptions attached", summary: "Universe, timeframe, signal, fills, risk, and validation status.", metrics: [["Protocols", "18"], ["Paper cohorts", "6"], ["Hidden rules", "0"]], rows: ["Premarket liquidity break and sweep", "Structural Fib continuation", "Close-to-next-open research"], next: "Compare only compatible samples and execution assumptions." },
  Backtest: { title: "Underlying strategy laboratory", summary: "Reproducible tests with costs, next-bar rules, and chronological holdouts.", metrics: [["Universe", "39 stocks/ETFs"], ["Costs", "Explicit"], ["Splits", "Chronological"]], rows: ["Downloadable trade ledger", "Every parameter trial retained", "Holdout never merged into training"], next: "Inspect stability across tickers and years." },
  "Options Backtest": { title: "Captured option-bar research", summary: "Point-in-time contract bars with historical NBBO absence preserved.", metrics: [["Archives", "37"], ["Fill truth", "Trade bars"], ["NBBO", "Unavailable"]], rows: ["Entry-time contract selection", "Missing bars never become zero returns", "Gross and friction stress kept separate"], next: "Use results to prioritize prospective validation." },
  "GEX Replay": { title: "Replay what the matrix knew then", summary: "Frozen public-OI gamma estimates without future positioning leakage.", metrics: [["Formula", "Signed GEX"], ["Direction", "Heuristic"], ["Missing", "Unknown"]], rows: ["Snapshot checksums protect lineage", "Spot and expiry context retained", "Dealer intent is never asserted"], next: "Compare frozen exposure with the price path that followed." },
  "Trident": { title: "Index exposure at a glance", summary: "SPY, QQQ, and IWM gamma structure without a forced common narrative.", metrics: [["Matrices", "3"], ["Levels", "Walls · flips"], ["Use", "Context"]], rows: ["SPY · broad-market hedges", "QQQ · technology concentration", "IWM · small-cap volatility"], next: "Treat disagreement as a risk clue, not a guaranteed trade." },
  "Chart Saves": { title: "Freeze the chart you actually saw", summary: "Ticker, timeframe, levels, notes, and evidence timestamp.", metrics: [["Demo saves", "5"], ["Ownership", "Private"], ["Replay", "Deterministic"]], rows: ["Morning plan", "Entry review", "Post-close lesson"], next: "Sign in to persist chart state.", locked: "Chart writes and deletion are disabled for guests." },
  Beliefs: { title: "Claims designed to be disproved", summary: "Hypotheses with evidence, blockers, and promotion criteria.", metrics: [["Active", "9"], ["Rejected", "7"], ["To paper", "3"]], rows: ["Fresh impulse may improve continuation", "Public OI is context, not dealer truth", "Overnight edge varies by ticker and cost"], next: "Advance a belief only when its predefined gate passes." },
};

const FALLBACK: Demo = { title: "Explore Cipher's research workflow", summary: "A deterministic representation of this private feature.", metrics: [["Mode", "Read-only demo"], ["Universe", "MAG7 + leaders"], ["Orders", "Disabled"]], rows: ["Point-in-time inputs", "Explicit uncertainty", "Human decision gate"], next: "Sign in for private data and interactive tools." };

export function GuestShowcase({ panel, ticker }: { panel: string; ticker: string }) {
  const content = DEMOS[panel] || FALLBACK;
  return <section data-testid="guest-showcase" data-guest-panel={panel} data-guest-source="demo" className="mx-auto flex w-full max-w-6xl flex-col gap-4">
    <div className="rounded-xl border p-5 sm:p-7" style={{ borderColor: "var(--line)", background: "linear-gradient(135deg, color-mix(in srgb, var(--accent) 11%, var(--panel)), var(--panel) 58%)" }}>
      <p className="text-[10px] font-bold uppercase tracking-[0.14em]" style={{ color: "var(--gold)" }}>Illustrative judge demo · {ticker} · read only</p>
      <h1 className="mt-3 text-2xl font-semibold sm:text-3xl">{panel}</h1>
      <p className="mt-2 text-base font-medium" style={{ color: "var(--text-dim)" }}>{content.title}</p>
      <p className="mt-3 max-w-3xl text-sm leading-6" style={{ color: "var(--text-dim)" }}>{content.summary}</p>
    </div>
    <div className="grid gap-3 sm:grid-cols-3">{content.metrics.map(([label, value]) => <div key={label} className="rounded-xl border p-4" style={{ borderColor: "var(--line)", background: "var(--panel)" }}><p className="text-[10px] font-bold uppercase tracking-[0.12em]" style={{ color: "var(--text-mute)" }}>{label}</p><p className="mt-2 text-lg font-semibold">{value}</p></div>)}</div>
    <div className="grid gap-4 lg:grid-cols-[1.35fr_1fr]">
      <div className="rounded-xl border p-5" style={{ borderColor: "var(--line)", background: "var(--panel)" }}><h2 className="text-sm font-semibold">What Cipher surfaces</h2><ul className="mt-4 space-y-3 text-sm" style={{ color: "var(--text-dim)" }}>{content.rows.map((row) => <li key={row} className="flex gap-3"><span style={{ color: "var(--accent)" }}>◆</span><span>{row}</span></li>)}</ul></div>
      <div className="rounded-xl border p-5" style={{ borderColor: "var(--line)", background: "var(--panel-2)" }}><h2 className="text-sm font-semibold">Next decision</h2><p className="mt-3 text-sm leading-6" style={{ color: "var(--text-dim)" }}>{content.next}</p>{content.locked && <div className="mt-4 rounded-lg border px-3 py-2 text-xs leading-5" style={{ borderColor: "var(--gold)", color: "var(--text-dim)" }}><strong style={{ color: "var(--gold)" }}>Guest boundary:</strong> {content.locked}</div>}</div>
    </div>
    <p className="text-[11px] leading-5" style={{ color: "var(--text-mute)" }}>Demo values are static and labelled—not current quotes, recommendations, or performance claims. Live market panels are marked separately. Cipher has no broker-order authority.</p>
  </section>;
}
