"use client";

import { useCallback, useEffect, useState } from "react";
import { addPortfolioRiskPosition, deletePortfolioRiskPosition, exportPortfolioRiskCsv, fetchPortfolioRisk, importPortfolioRiskCsv, setPortfolioRiskCash, type PortfolioRiskInput, type PortfolioRiskStatus } from "@/lib/api";

const money = (value: number | null | undefined) => value == null ? "—" : new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);
const num = (value: number | null | undefined) => value == null ? "unknown" : value.toFixed(2);
const field = "rounded px-2 py-1.5 text-[11px]";

export function PortfolioRisk() {
  const [data, setData] = useState<PortfolioRiskStatus | null>(null);
  const [error, setError] = useState("");
  const [form, setForm] = useState<PortfolioRiskInput>({ asset_type: "stock", ticker: "", quantity: 1, entry_price: 0, strategy: "Ungrouped" });
  const reload = useCallback((signal?: AbortSignal) => fetchPortfolioRisk(signal).then(setData), []);
  useEffect(() => { const c = new AbortController(); reload(c.signal).catch((e) => { if (!c.signal.aborted) setError(e instanceof Error ? e.message : "Portfolio unavailable"); }); return () => c.abort(); }, [reload]);
  async function add(event: React.FormEvent) { event.preventDefault(); try { await addPortfolioRiskPosition(form); await reload(); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "Could not add position"); } }
  async function download() { const out = await exportPortfolioRiskCsv(); const a = document.createElement("a"); a.href = URL.createObjectURL(new Blob([out.csv], { type: "text/csv" })); a.download = out.filename; a.click(); URL.revokeObjectURL(a.href); }
  async function upload(file?: File) { if (!file) return; try { await importPortfolioRiskCsv(await file.text()); await reload(); } catch (e) { setError(e instanceof Error ? e.message : "CSV import failed"); } }
  const style = { background: "var(--panel-2)", border: "1px solid var(--line)" };
  return <div className="space-y-4" style={{ color: "var(--text)" }}>
    <section className="rounded-xl border p-4" style={{ background: "var(--panel)", borderColor: "var(--line)" }}><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-base font-semibold">Manual portfolio risk</h2><p className="mt-1 max-w-3xl text-[11px]" style={{ color: "var(--text-dim)" }}>{data?.caveat ?? "Loading manual stocks-and-options ledger…"}</p><p className="mt-1 text-[10px]" style={{ color: "var(--gold)" }}>Research only · no broker sync · no order actions</p></div><div className="flex gap-2"><button type="button" onClick={download} className={field} style={style}>Export CSV</button><label className={`${field} cursor-pointer`} style={style}>Import CSV<input type="file" accept=".csv,text/csv" className="hidden" onChange={(e) => upload(e.target.files?.[0])} /></label></div></div></section>
    {data && <><div className="grid grid-cols-2 gap-2 md:grid-cols-4 xl:grid-cols-6">{[["Net liq", money(data.summary.net_liquidating_value)], ["Cash", money(data.cash)], ["Position value", money(data.summary.signed_market_value)], ["Unrealized", money(data.summary.unrealized_pnl)], ["Delta", num(data.summary.aggregate_greeks.delta)], ["Theta/day", num(data.summary.aggregate_greeks.theta)]].map(([label, value]) => <div key={label} className="rounded-lg p-3" style={style}><p className="text-[9px] uppercase" style={{ color: "var(--text-mute)" }}>{label}</p><p className="mt-1 font-mono text-sm">{value}</p></div>)}</div>
    <section className="rounded-xl border p-4" style={{ background: "var(--panel)", borderColor: "var(--line)" }}><div className="mb-3 flex items-center gap-2"><h3 className="text-xs font-semibold">Declared cash</h3><input aria-label="Declared cash" type="number" defaultValue={data.cash} className={field} style={style} onBlur={async (e) => { await setPortfolioRiskCash(Number(e.target.value)); await reload(); }} /></div><form onSubmit={add} className="flex flex-wrap items-end gap-2"><label className="text-[10px]">Strategy<input value={form.strategy} onChange={(e) => setForm({ ...form, strategy: e.target.value })} className={`block ${field}`} style={style} /></label><label className="text-[10px]">Asset<select value={form.asset_type} onChange={(e) => setForm({ ...form, asset_type: e.target.value as "stock" | "option" })} className={`block ${field}`} style={style}><option value="stock">Stock</option><option value="option">Option</option></select></label><label className="text-[10px]">Ticker<input required value={form.ticker} onChange={(e) => setForm({ ...form, ticker: e.target.value.toUpperCase() })} className={`block w-20 ${field}`} style={style} /></label><label className="text-[10px]">Qty (+long/−short)<input required type="number" value={form.quantity} onChange={(e) => setForm({ ...form, quantity: Number(e.target.value) })} className={`block w-24 ${field}`} style={style} /></label><label className="text-[10px]">Entry<input required type="number" min="0" step="any" value={form.entry_price} onChange={(e) => setForm({ ...form, entry_price: Number(e.target.value) })} className={`block w-24 ${field}`} style={style} /></label>{form.asset_type === "option" && <><label className="text-[10px]">Type<select value={form.option_type ?? "call"} onChange={(e) => setForm({ ...form, option_type: e.target.value as "call" | "put" })} className={`block ${field}`} style={style}><option value="call">Call</option><option value="put">Put</option></select></label><label className="text-[10px]">Strike<input required type="number" step="any" value={form.strike ?? ""} onChange={(e) => setForm({ ...form, strike: Number(e.target.value) })} className={`block w-20 ${field}`} style={style} /></label><label className="text-[10px]">Expiration<input required type="date" value={form.expiration ?? ""} onChange={(e) => setForm({ ...form, expiration: e.target.value })} className={`block ${field}`} style={style} /></label></>}<button className={`${field} font-semibold`} style={{ background: "var(--accent)", color: "white" }}>Add manual position</button></form>{error && <p className="mt-2 text-[11px]" style={{ color: "var(--neg)" }}>{error}</p>}</section>
    <section className="overflow-x-auto rounded-xl border" style={{ borderColor: "var(--line)" }}><table className="w-full min-w-[900px] text-[11px]"><thead style={{ background: "var(--panel-2)" }}><tr>{["Group", "Instrument", "Qty", "Entry", "Mark/source", "Value", "P&L", "Δ", "Γ", "Θ", ""].map((x) => <th key={x} className="p-2 text-left">{x}</th>)}</tr></thead><tbody>{data.positions.map((p) => <tr key={p.id} className="border-t" style={{ borderColor: "var(--line)" }}><td className="p-2">{p.strategy}</td><td className="p-2 font-mono">{p.ticker} {p.asset_type === "option" ? `${p.expiration} ${p.strike}${p.option_type?.[0].toUpperCase()}` : "stock"}</td><td className="p-2">{p.quantity}</td><td className="p-2">{money(p.entry_price)}</td><td className="p-2">{money(p.current_mark)}<br/><span style={{ color: "var(--text-mute)" }}>{p.mark_source ?? "unknown"}</span></td><td className="p-2">{money(p.market_value)}</td><td className="p-2">{money(p.unrealized_pnl)}</td><td className="p-2">{num(p.greeks.delta)}</td><td className="p-2">{num(p.greeks.gamma)}</td><td className="p-2">{num(p.greeks.theta)}</td><td className="p-2"><button type="button" onClick={async () => { await deletePortfolioRiskPosition(p.id); await reload(); }} style={{ color: "var(--neg)" }}>Delete</button></td></tr>)}</tbody></table>{!data.positions.length && <p className="p-4 text-[11px]" style={{ color: "var(--text-mute)" }}>No manual positions.</p>}</section>
    <div className="grid gap-3 lg:grid-cols-3"><Card title="Expiration calendar">{data.expiration_calendar.map((x) => <p key={x.expiration}>{x.expiration} · {x.positions} legs · {x.short_contracts} short</p>)}</Card><Card title="Delta-dollar concentration">{data.concentration.map((x) => <p key={x.ticker}>{x.ticker} · {money(x.delta_dollars)} · {x.weight_pct?.toFixed(1) ?? "—"}%</p>)}</Card><Card title={`Exceptions (${data.exceptions.length})`}>{data.exceptions.map((x, i) => <p key={`${x.kind}-${i}`} style={{ color: "var(--gold)" }}>{x.ticker} · {x.kind} · {x.detail}</p>)}</Card></div></>}
  </div>;
}

function Card({ title, children }: { title: string; children: React.ReactNode }) { return <section className="min-h-28 rounded-xl border p-4 text-[11px]" style={{ background: "var(--panel)", borderColor: "var(--line)" }}><h3 className="mb-2 text-xs font-semibold">{title}</h3><div className="space-y-1" style={{ color: "var(--text-dim)" }}>{children}</div></section>; }
