"use client";
/* Inline data-URI SVGs are immutable journal evidence, not optimizable remote images. */
/* eslint-disable @next/next/no-img-element */
import { useCallback, useEffect, useState } from "react";
import { createJournalEntry, deleteJournalEntry, fetchJournal, updateJournalEntry, type JournalEntry } from "@/lib/api";

const style = { background: "var(--panel-2)", border: "1px solid var(--line)" };
export function TraderJournal({ ticker }: { ticker: string }) {
  const [entries, setEntries] = useState<JournalEntry[]>([]); const [allTickers, setAllTickers] = useState(true); const [error, setError] = useState("");
  const [title, setTitle] = useState(""); const [thesis, setThesis] = useState(""); const [direction, setDirection] = useState<"long" | "short" | "neutral">("long"); const [entryPrice, setEntryPrice] = useState(""); const [invalidation, setInvalidation] = useState(""); const [targets, setTargets] = useState(""); const [tags, setTags] = useState("");
  const [optionLegs, setOptionLegs] = useState("");
  const reload = useCallback((signal?: AbortSignal) => fetchJournal(allTickers ? undefined : ticker, signal).then((d) => setEntries(d.entries)), [allTickers, ticker]);
  useEffect(() => { const c = new AbortController(); Promise.resolve().then(() => reload(c.signal)).catch((e) => { if (!c.signal.aborted) setError(e instanceof Error ? e.message : "Journal unavailable"); }); return () => c.abort(); }, [reload]);
  async function add(e: React.FormEvent) { e.preventDefault(); try { const legs = optionLegs.split(/\n+/).map((line) => line.trim()).filter(Boolean).map((line) => { const [contract_symbol, side, quantity, entry_mark] = line.split(",").map((x) => x.trim()); return { contract_symbol, side: side as "buy" | "sell", quantity: Number(quantity), multiplier: 100, entry_mark: entry_mark ? Number(entry_mark) : null, entry_mark_type: "manual" }; }); await createJournalEntry({ ticker, title, thesis, direction, status: entryPrice || legs.length ? "open" : "planned", entry_price: entryPrice ? Number(entryPrice) : null, entry_at: entryPrice || legs.length ? new Date().toISOString() : null, invalidation: invalidation ? Number(invalidation) : null, targets: targets.split(",").map(Number).filter(Number.isFinite), tags: tags.split(",").map((x) => x.trim()).filter(Boolean), legs }); setTitle(""); setThesis(""); setOptionLegs(""); await reload(); } catch (x) { setError(x instanceof Error ? x.message : "Could not save"); } }
  return <div className="space-y-4" style={{ color: "var(--text)" }}><section className="rounded-xl p-4" style={{ background: "var(--panel)", border: "1px solid var(--line)" }}><div className="flex items-start justify-between gap-3"><div><h1 className="text-xl font-bold">Trader journal</h1><p className="mt-1 text-[11px]" style={{ color: "var(--text-dim)" }}>Links thesis, levels, manual/paper references, chart state, and post-trade review. MFE/MAE is underlying-price context—not option-premium P/L.</p></div><label className="text-[10px]"><input type="checkbox" checked={allTickers} onChange={(e) => setAllTickers(e.target.checked)} /> All tickers</label></div></section>
  <form onSubmit={add} className="grid gap-2 rounded-xl p-4 md:grid-cols-4" style={{ background: "var(--panel)", border: "1px solid var(--line)" }}><input required value={title} onChange={(e) => setTitle(e.target.value)} placeholder={`${ticker} journal title`} className="rounded px-2 py-2 text-xs md:col-span-2" style={style}/><select value={direction} onChange={(e) => setDirection(e.target.value as typeof direction)} className="rounded px-2 py-2 text-xs" style={style}><option>long</option><option>short</option><option>neutral</option></select><input value={entryPrice} onChange={(e) => setEntryPrice(e.target.value)} placeholder="Underlying entry (optional)" type="number" step="any" className="rounded px-2 py-2 text-xs" style={style}/><textarea value={thesis} onChange={(e) => setThesis(e.target.value)} placeholder="Thesis and evidence" className="rounded px-2 py-2 text-xs md:col-span-2" style={style}/><input value={invalidation} onChange={(e) => setInvalidation(e.target.value)} placeholder="Invalidation" type="number" step="any" className="rounded px-2 py-2 text-xs" style={style}/><input value={targets} onChange={(e) => setTargets(e.target.value)} placeholder="Targets: 100, 105" className="rounded px-2 py-2 text-xs" style={style}/><input value={tags} onChange={(e) => setTags(e.target.value)} placeholder="Tags, comma separated" className="rounded px-2 py-2 text-xs md:col-span-3" style={style}/><details className="md:col-span-4 rounded p-2" style={style}><summary className="cursor-pointer text-[11px]">Exact option legs (optional)</summary><textarea value={optionLegs} onChange={(e) => setOptionLegs(e.target.value)} placeholder="NVDA260821C00230000,buy,1,1.25&#10;NVDA260821C00235000,sell,1,0.45" className="mt-2 min-h-16 w-full rounded p-2 font-mono text-[11px]" style={style}/><p className="text-[10px]" style={{color:"var(--text-mute)"}}>One OCC contract per line: symbol, buy/sell, quantity, entry mark. Captured marks are valuation evidence, not fills.</p></details><button className="rounded px-3 py-2 text-xs font-semibold md:col-start-4" style={{ background: "var(--accent)", color: "white" }}>Save journal entry</button></form>
  <div className="grid gap-3 xl:grid-cols-2">{entries.map((row) => <article key={row.id} className="rounded-xl p-4 text-[11px]" style={{ background: "var(--panel)", border: "1px solid var(--line)" }}><div className="flex justify-between gap-2"><div><b className="text-sm">{row.ticker} · {row.title}</b><p style={{ color: "var(--text-mute)" }}>{row.status} · {row.direction} · {row.setup ?? "unclassified"} · {row.created_at}</p></div><button type="button" onClick={async () => { await deleteJournalEntry(row.id); await reload(); }} style={{ color: "var(--neg)" }}>Delete</button></div><p className="my-2 whitespace-pre-wrap">{row.thesis || "No thesis recorded."}</p><div className="grid grid-cols-2 gap-1"><span>Entry {row.entry_price ?? "—"}</span><span>Invalidation {row.invalidation ?? "—"}</span><span>Targets {row.targets.join(", ") || "—"}</span><span>Tags {row.tags.join(", ") || "—"}</span><span>Underlying MFE {row.excursion.mfe_pct?.toFixed(2) ?? "—"}%</span><span>Underlying MAE {row.excursion.mae_pct?.toFixed(2) ?? "—"}%</span><span>Position ref {row.position_id ?? "—"}</span><span>Signal ref {row.signal_id ?? "—"}</span></div>{row.legs.length > 0 && <details className="mt-3 rounded p-2" style={style}><summary className="cursor-pointer font-semibold">Option marks · {row.option_excursion.status} · {row.option_excursion.coverage?.calculated_legs ?? 0}/{row.legs.length} legs</summary>{row.option_excursion.legs.map((leg) => <div key={leg.contract_symbol} className="mt-2 border-t pt-2" style={{borderColor:"var(--line)"}}><b>{leg.contract_symbol}</b> · {leg.status} · {leg.events} events{leg.excursions?.bid && <p>Bid MFE/MAE {leg.excursions.bid.mfe_pct?.toFixed(2) ?? "—"}% / {leg.excursions.bid.mae_pct?.toFixed(2) ?? "—"}% · ${leg.excursions.bid.mfe_dollars?.toFixed(2) ?? "—"} / ${leg.excursions.bid.mae_dollars?.toFixed(2) ?? "—"}</p>}</div>)}<p className="mt-2 text-[9.5px]" style={{color:"var(--text-mute)"}}>{row.option_excursion.caveat}</p></details>}{row.chart_snapshot_svg && <img className="mt-3 w-full rounded" alt={`${row.ticker} saved chart-state evidence`} src={`data:image/svg+xml;charset=utf-8,${encodeURIComponent(row.chart_snapshot_svg)}`}/>} {row.status !== "closed" && <button type="button" onClick={async () => { await updateJournalEntry(row.id, { status: "closed", exit_at: new Date().toISOString(), exit_reason: "manual review close" }); await reload(); }} className="mt-3 rounded px-2 py-1" style={style}>Mark reviewed/closed</button>}</article>)}</div>{!entries.length && <p className="text-xs" style={{ color: "var(--text-mute)" }}>No journal entries yet.</p>}{error && <p style={{ color: "var(--neg)" }}>{error}</p>}</div>;
}
