"use client";

import { useCallback, useEffect, useState } from "react";
import { addWatchlistMember, createWatchlist, deleteSavedScreen, deleteServerWatchlist, fetchQuote, fetchWatchlists, removeWatchlistMember, runSavedScreen, saveScreen, type ScreenResult, type WatchlistsPayload } from "@/lib/api";
import { loadWatchlistTickers, saveWatchlistTickers } from "@/lib/watchlist";

const style = { background: "var(--panel-2)", border: "1px solid var(--line)" };
export function Watchlists() {
  const [data, setData] = useState<WatchlistsPayload | null>(null);
  const [active, setActive] = useState(""); const [listName, setListName] = useState(""); const [ticker, setTicker] = useState(""); const [quotes, setQuotes] = useState<Record<string, { price: number; change: number; as_of: string }>>({});
  const [screenName, setScreenName] = useState(""); const [minChange, setMinChange] = useState(""); const [minScore, setMinScore] = useState(""); const [screenResult, setScreenResult] = useState<ScreenResult | null>(null); const [error, setError] = useState("");
  const reload = useCallback(async (signal?: AbortSignal) => { const result = await fetchWatchlists(signal); setData(result); setActive((current) => current || result.watchlists[0]?.id || ""); return result; }, []);
  useEffect(() => { const c = new AbortController(); Promise.resolve().then(() => reload(c.signal)).then(async (result) => { if (!result.watchlists.length) { const legacy = loadWatchlistTickers(); const created = await createWatchlist("Default"); for (const symbol of legacy) await addWatchlistMember(created.id, symbol); await reload(); } }).catch((e) => { if (!c.signal.aborted) setError(e instanceof Error ? e.message : "Watchlists unavailable"); }); return () => c.abort(); }, [reload]);
  const selected = data?.watchlists.find((x) => x.id === active);
  useEffect(() => { if (!selected) return; saveWatchlistTickers(selected.tickers); let cancelled = false; Promise.all(selected.tickers.map(async (symbol) => { try { const q = await fetchQuote(symbol); return [symbol, { price: q.price_context, change: q.day_change_pct, as_of: q.as_of }] as const; } catch { return null; } })).then((rows) => { if (!cancelled) setQuotes(Object.fromEntries(rows.filter((x): x is NonNullable<typeof x> => x !== null))); }); return () => { cancelled = true; }; }, [selected]);
  async function mutate(task: Promise<unknown>) { try { await task; await reload(); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "Request failed"); } }
  async function createScreen() { const criteria: Record<string, number | boolean> = { optionable: true }; if (minChange !== "") criteria.day_change_min = Number(minChange); if (minScore !== "") criteria.scanner_score_min = Number(minScore); await mutate(saveScreen({ name: screenName, watchlist_id: active || undefined, criteria })); setScreenName(""); }
  return <div className="space-y-4" style={{ color: "var(--text)" }}><section className="rounded-xl p-4" style={{ background: "var(--panel)", border: "1px solid var(--line)" }}><h1 className="text-xl font-bold">Named watchlists & screens</h1><p className="mt-1 text-[11px]" style={{ color: "var(--text-dim)" }}>Stored on this private server. Saved screens retain their exact criteria and ticker input set. They observe; they never trade.</p></section>
  <div className="flex flex-wrap gap-2"><select value={active} onChange={(e) => setActive(e.target.value)} className="rounded px-3 py-2 text-xs" style={style}>{data?.watchlists.map((x) => <option value={x.id} key={x.id}>{x.name} ({x.tickers.length})</option>)}</select><input value={listName} onChange={(e) => setListName(e.target.value)} placeholder="New list name" className="rounded px-3 py-2 text-xs" style={style}/><button type="button" onClick={() => mutate(createWatchlist(listName))} className="rounded px-3 py-2 text-xs" style={style}>Create list</button>{selected && <button type="button" onClick={() => mutate(deleteServerWatchlist(selected.id))} className="rounded px-3 py-2 text-xs" style={{ ...style, color: "var(--neg)" }}>Delete list</button>}</div>
  {selected && <section className="rounded-xl p-4" style={{ background: "var(--panel)", border: "1px solid var(--line)" }}><form onSubmit={(e) => { e.preventDefault(); mutate(addWatchlistMember(selected.id, ticker)); setTicker(""); }} className="mb-3 flex gap-2"><input value={ticker} onChange={(e) => setTicker(e.target.value.toUpperCase())} placeholder="Add ticker" className="rounded px-3 py-2 text-xs" style={style}/><button className="rounded px-3 py-2 text-xs font-semibold" style={{ background: "var(--accent)", color: "white" }}>Add</button></form><div className="overflow-x-auto"><table className="w-full min-w-[520px] text-xs"><thead><tr>{["Ticker", "Price", "Day", "As of", ""].map((x) => <th key={x} className="p-2 text-left">{x}</th>)}</tr></thead><tbody>{selected.tickers.map((symbol) => <tr key={symbol} className="border-t" style={{ borderColor: "var(--line)" }}><td className="p-2 font-mono">{symbol}</td><td className="p-2">{quotes[symbol]?.price?.toFixed(2) ?? "—"}</td><td className="p-2">{quotes[symbol]?.change?.toFixed(2) ?? "—"}%</td><td className="p-2 text-[10px]">{quotes[symbol]?.as_of ?? "unknown"}</td><td className="p-2"><button type="button" onClick={() => mutate(removeWatchlistMember(selected.id, symbol))} style={{ color: "var(--neg)" }}>Remove</button></td></tr>)}</tbody></table></div></section>}
  <section className="rounded-xl p-4" style={{ background: "var(--panel)", border: "1px solid var(--line)" }}><h2 className="text-sm font-semibold">Saved multi-factor screens</h2><div className="mt-3 flex flex-wrap items-end gap-2"><label className="text-[10px]">Name<input value={screenName} onChange={(e) => setScreenName(e.target.value)} className="block rounded px-2 py-1.5" style={style}/></label><label className="text-[10px]">Min day change %<input type="number" step="any" value={minChange} onChange={(e) => setMinChange(e.target.value)} className="block w-28 rounded px-2 py-1.5" style={style}/></label><label className="text-[10px]">Min latest scan score<input type="number" step="any" value={minScore} onChange={(e) => setMinScore(e.target.value)} className="block w-28 rounded px-2 py-1.5" style={style}/></label><button type="button" onClick={createScreen} className="rounded px-3 py-2 text-xs" style={style}>Save screen</button></div><div className="mt-4 space-y-2">{data?.screens.map((screen) => <div key={screen.id} className="flex flex-wrap items-center justify-between gap-2 rounded p-2 text-[11px]" style={style}><span><b>{screen.name}</b> · {JSON.stringify(screen.criteria)}</span><span className="flex gap-3"><button type="button" onClick={async () => setScreenResult(await runSavedScreen(screen.id))}>Run</button><button type="button" onClick={() => mutate(deleteSavedScreen(screen.id))} style={{ color: "var(--neg)" }}>Delete</button></span></div>)}</div>{screenResult && <div className="mt-4 rounded p-3 text-[11px]" style={style}><p><b>{screenResult.name}</b> · {screenResult.matches.length}/{screenResult.evaluated} matched · {screenResult.generated_at}</p><p className="mt-1" style={{ color: "var(--text-mute)" }}>Input snapshot: {screenResult.reproducible_inputs.tickers.join(", ") || "empty"}</p>{screenResult.matches.map((row) => <p key={row.ticker}>{row.ticker} · {row.price.toFixed(2)} · {row.day_change_pct.toFixed(2)}% · scan {row.scanner_score ?? "unknown"}</p>)}</div>}</section>{error && <p className="text-xs" style={{ color: "var(--neg)" }}>{error}</p>}</div>;
}
